ARG KINESIS_CORE_IMAGE=abxit/kinesis-core:5b08ad3

FROM ${KINESIS_CORE_IMAGE} AS core

FROM golang:1.26 AS builder
ENV DEBIAN_FRONTEND=noninteractive
ARG VERSION=develop
RUN apt-get update && apt-get upgrade -y && apt-get clean

# install PGSQL for integration testing
RUN apt-get install -y --no-install-suggests --no-install-recommends postgresql && apt-get clean
COPY pg_hba.conf /etc/postgresql/13/main/pg_hba.conf

# install modules
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN /etc/init.d/postgresql start 13 \
    && go test -race -cover ./services/horizon/...

ENV CGO_ENABLED=0
ENV HORIZON_VERSION="-X=github.com/stellar/go/support/app.version=$VERSION"
ENV GOFLAGS="-ldflags=$HORIZON_VERSION"
RUN go install ./...

FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive

EXPOSE 8000
EXPOSE 9473

# ca-certificates are required to make tls connections
RUN apt-get update && apt-get upgrade -y \
  && apt-get install -y --no-install-recommends ca-certificates curl wget gnupg apt-utils jq libpq5 libc++1 \
  && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY --from=core /usr/bin/stellar-core /usr/bin/stellar-core
COPY --from=builder /go/bin/horizon \
  /go/bin/friendbot \
  /go/bin/stellar-archivist \
  /go/bin/stellar-hd-wallet \
  /usr/bin/

ENTRYPOINT ["horizon"]
